AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ordersapi

  Sample SAM Template for ordersapi
Globals:
  Function:
      Runtime: java8
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          ORDERS_TABLE: !Ref OrdersTable

Resources:
  OrdersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  CreateOrdersFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi
      Handler: com.aws.lambda.app.CreateOrderLambda::createOrder
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Events: 
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: POST
  ReadOrdersFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ordersapi
      Handler: com.aws.lambda.app.ReadOrderLambda::getOrder
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref OrdersTable
      Events: 
        OrderEvents:
          Type: Api
          Properties:
            Path: /orders
            Method: GET
Outputs:
  CreateOrdersAPI:
    Description: "API Gateway endpoint url for create order function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/orders"